### ISSUE TITLE
Improve mnemonic handling

### ISSUE THREAD

**Issue by jimmychu0807** [CESSProject/cess-js-sdk#2]
Currently mnemonic is passed in to be used when sending transactions to CESS blockchain.

- It will be better to use private key instead of mnemonic. This is because Substrate account allows deriving multiple accounts from the same mnemonic.

- It will be better to config the private key only once when initializing the API. It can then be used afterward without users have to pass in the mnemonic/private key every time when a transaction is sent.

**Comment by lanmeng656** [comment]
@jimmychu0807  Thank you for your suggestion. 

- I am using Keyring.createFromUri, which supports private keys, but I think mnemonics are easier to obtain and more convenient. As for Substrate account allows deriving multiple accounts from the same mnemonic, it is not too significant to affect.

- This is for flexibility reasons, as if the user's business logic is multiple accounts, then this approach is more convenient.

I will keep trying, and if your suggestion is indeed better, I will use it in the next version.
