### ISSUE TITLE
File not getting downloaded for cess-js-sdk v0.8.10

### ISSUE THREAD

**Issue by tehsunnliu** [CESSProject/cess-js-sdk#4]
Hi @lanmeng656, I was trying to use the cess-js-sdk v0.8.10 and I was facing some issues downloading the file. The SDK executes with no error and shows that the file is downloaded, however, the file is never in the location. 

![img_v3_0287_657a34fe-2fda-4aa7-aa2a-ed1d8a4d4bix](https://github.com/CESSProject/cess-js-sdk/assets/15224865/ac5edf4c-a415-4687-8e49-cd3bb173fd21)

**Comment by lanmeng656** [comment]
This bug has been fixed and updated to v0.8.12. Thank you.
